DROP TABLE IF EXISTS filmsNew, films, UserTable, Friendship,
 Likes, Film, CategoryRank, Genre CASCADE;

CREATE TABLE UserTable (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email varchar (100) NOT NULL,
        login varchar (70) NOT NULL,
        name varchar (50) NOT NULL,
        birthday date
);


CREATE TABLE Genre (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        genre varchar(100) NOT NULL
);

CREATE TABLE CategoryRank (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        categoryRank varchar(200) NOT NULL
);

CREATE TABLE Film (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nameId varchar (50) NOT NULL,
        description varchar (200) NOT NULL,
        releaseDate date,
        duration integer,
        genre integer references Genre (id),
        categoryRank integer references CategoryRank (id)
);


CREATE TABLE Friendship (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        userId integer references UserTable (id),
        userFriendId integer references UserTable (id),
        userFriendshipStatus boolean default false,
        FriendFriendshipStatus boolean default false
);

CREATE TABLE Likes (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        userId integer references UserTable (id),
        filmId integer references Film (id),
        likeOrNot boolean default false
);



